name: Submit Ollama package to WinGet community repository

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-winget:
    name: Publish to winget repository
    runs-on: windows-latest
    steps:
      - name: Sync fork
        run: gh repo sync <repo-owner>/winget-pkgs -b master
        env:
          GH_TOKEN: ${{ secrets.WINGET_GITHUB_TOKEN }}
      - name: Submit package using wingetcreate
        run: |
          $packageId = "Ollama.Ollama"

          # Fetching latest stable release from GitHub
          $github = Invoke-RestMethod -uri "https://api.github.com/repos/ollama/ollama/releases"
          $targetRelease = $github | Where-Object {$_.prerelease -eq $false} | Select-Object -First 1
          $installerUrl = $targetRelease | Select-Object -ExpandProperty assets -First 1 | Where-Object -Property name -eq 'OllamaSetup.exe' | Select-Object -ExpandProperty browser_download_url
          $packageVersion = $targetRelease.tag_name.Trim("v")

          # Update package using wingetcreate
          Invoke-WebRequest https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update $packageId --version $packageVersion --urls "$installerUrl|x64" --submit --token "${{ secrets.WINGET_GITHUB_TOKEN }}"
